version: "3.8"
services:
  api:
    container_name: inference-demo-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
      environment:
        AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
        AWS_SQS_ENDPOINT: ${AWS_SQS_ENDPOINT}
        BUCKET_NAME: ${BUCKET_NAME}
        QUEUE_NAME: ${QUEUE_NAME}
        MESSAGE_GROUP_ID: ${MESSAGE_GROUP_ID}
        DEADLETTER_QUEUE_NAME: ${DEADLETTER_QUEUE_NAME}
        ACCOUNT_ID: ${ACCOUNT_ID}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      volumes:
