AWSTemplateFormatVersion: 2010-09-09

Mappings:
  DomainMappings:
    "XXX": # 開発環境
      AppDomainName: dev.sample-detection.api.tk.com
    "YYY": # 本番環境
      AppDomainName: sample-detection.api.tk.com

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !FindInMap [DomainMappings, !Ref "AWS::AccountId", AppDomainName]
      ValidationMethod: DNS
      Tags:
        - Key: "CmBillingGroup"
          Value: "sample-detection-api"
