FROM python:3.8

ARG AWS_ROLE_ARN
ARG DEPLOY_KEY

ENV APP_PATH=/code \
  PYTHONPATH=.

WORKDIR /root/.aws

RUN if [ "${AWS_ROLE_ARN}" != "" ]; then \
  echo "[default]\n\
  credential_source = Environment\n\
  role_arn = ${AWS_ROLE_ARN}\n\
  region = ap-northeast-1\n"\
  > config; \
  fi

WORKDIR /root/.ssh

RUN echo $DEPLOY_KEY | base64 --decode > ./id_rsa \
  && ssh-keyscan github.com >> ./known_hosts \
  && chmod 600 ./*

WORKDIR $APP_PATH
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y libgl1-mesa-dev poppler-utils poppler-data && \
  pip install poetry && \
  poetry config virtualenvs.create false

COPY ./worker  .

EXPOSE 8080
